# Generated by Django 6.1 on 2026-09-12 22:17

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_user_cmd_pin_hash'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', db.models.EmailOrUsernameUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='crmtriprecord',
            name='tpms_fl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crmtriprecord',
            name='tpms_fr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crmtriprecord',
            name='tpms_rl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crmtriprecord',
            name='tpms_rr',
            field=models.IntegerField(default=0),
        ),
    ]
