# Generated by Django 6.1 on 2026-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_evinfo_lease_contract_alter_alerthistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Charge stop'), (2, 'Charge start'), (3, 'Charge cable reminder'), (4, 'A/C on'), (5, 'A/C off'), (6, 'Configuration read'), (7, 'A/C auto off'), (8, 'Quick charge stop'), (9, 'Battery heater start'), (10, 'Battery heater stop'), (11, 'Charge start 80%'), (12, 'Door unlock'), (13, 'Door lock'), (14, 'Horn & Light'), (15, 'Stop Horn & Light'), (16, 'Remote Start'), (17, 'Remote Stop'), (18, 'Configuration Updated'), (19, 'Received new data'), (20, 'Burglar alert'), (21, 'Tow Notification'), (22, 'End Battery Lease Contract'), (92, 'TCU Configuration error'), (93, 'Remote Start/Stop error'), (94, 'Horn & Light error'), (95, 'Door Lock/Unlock error'), (96, 'Charge error'), (97, 'A/C error'), (98, 'Command timeout'), (99, 'Error')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn'), (10, 'Lights'), (11, 'Horn & Lights'), (12, 'Stop Horn & light'), (13, 'Remote Start'), (14, 'Remote Stop'), (15, 'Configuration Request'), (16, 'End Battery Lease Contract')], default=0),
        ),
        migrations.AlterField(
            model_name='commandtimersetting',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn'), (10, 'Lights'), (11, 'Horn & Lights'), (12, 'Stop Horn & light'), (13, 'Remote Start'), (14, 'Remote Stop'), (15, 'Configuration Request'), (16, 'End Battery Lease Contract')], default=0),
        ),
    ]
