import decimal
from typing import Dict, Any, Tuple

from tculink.gdc_proto import WH_PER_GID_GEN1
from tculink.gdc_proto.acp245 import parser, composer


def parse_auth_ev_pload(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    version, consumed = parser.parse_version_ficosa(acp_encoded_data, offset)
    result["version"] = version
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    return result, offset

def parse_ev_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    return result, offset

def parse_car_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    version, consumed = parser.parse_version_ficosa(acp_encoded_data, offset)
    result["version"] = version
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    return result, offset


def parse_probe_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    version, consumed = parser.parse_version_ficosa(acp_encoded_data, offset)
    result["version"] = version
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    return result, offset

def parse_config_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    return result, offset

def parse_ev_info(data: bytes, offset: int) -> Tuple[dict, int]:
    d, all_li = parser._decode_ie_element(data, offset, 0, parser.IE_Element())
    d = d["value"]
    if len(d) < 0x16:
        raise Exception("Not enough bytes in EV data")
    # Format Doc: EVInfo.ods @ nissan-leaf-tcu repo

    pluggedin = (d[0] & 0b00001001) == 9
    charging = ((d[0] & 0b01000000) >> 6) == 1
    ignition = ((d[0] & 0b00100000) >> 5) == 1
    # TODO quickcharge
    quick_charging = False
    finish_flag = (d[0] & 0b10000000) > 0
    acstate = ((d[0] & 0b00000010) >> 1) == 1

    chargebars = 0
    chgbar_multiplier = (d[9] & 0b11111000) >> 3
    if 0x1F > chgbar_multiplier > 0:
        chargebars = (((d[9] & 0b00000111) << 3) | ((d[10] & 0b11100000) >> 5)) / chgbar_multiplier

    drive_status = (d[4] & 0b11111000) >> 3

    soh = ((d[6] & 0b00111111) << 1) | ((d[7] & 0b10000000) >> 7)

    soc = (((d[7] & 0b01111111) << 3) | ((d[8] & 0b11100000) >> 3))/10.0
    soc_display_int = d[11]
    if soc_display_int > 100:
        soc_display_int = 0
    soc_display = ((d[17] << 4) | ((d[18] & 0b11110000) >> 4))
    if soc_display == 0:
        soc_display = soc_display_int
    else:
        soc_display = soc_display / 8.00

    gids = (d[5] << 2) | ((d[6] & 0b11000000) >> 6)

    acoff = (d[19] << 2) | ((d[20] & 0b11000000) >> 6)
    acon = ((d[20] & 0b00111111) << 4) | ((d[21] & 0b11110000) >> 4)

    capacity_bars_raw = d[12]
    # 241-255 is faulty data
    capacity_bars = 0 if capacity_bars_raw > 240 else (capacity_bars_raw - 1) // 20 + 1



    range_acon = int(decimal.Decimal(
        (acon*((gids*WH_PER_GID_GEN1)/10000))).__round__(0))
    range_acoff = int(decimal.Decimal(
        (acoff*((gids*WH_PER_GID_GEN1)/10000))).__round__(0))

    chg_time_1 = ((d[2] & 0b00011111) << 6) | ((d[3] & 0b11111100) >> 2)
    chg_time_2 = (d[1] << 3) | ((d[2] & 0b11100000) >> 5)
    chg_time_3 = (d[14] << 3) | ((d[15] & 0b11100000) >> 5)

    if finish_flag:
        charging = False
        quick_charging = False

    # 6.6 kW OBC flag
    obc_flag = (d[15] & 0x02) != 0

    cabin_temp = 0.0

    # GIDS when new, max energy at SOH 100%
    gids_when_new = (
        ((d[21] & 0b00001111) << 6) | ((d[22] & 0b11111100) >> 2)
    )

    lease_contract = (d[22] & 0b00000010) >> 1

    # ZE1!
    if len(d) == 24:
        temp_data = d[23]
        if temp_data > 0:
            cabin_temp = float(temp_data/2) - 40.0

    return {
        "acon": range_acon,
        "acoff": range_acoff,
        "pluggedin":pluggedin,
        "charging": charging,
        "quick_charging": quick_charging,
        "finish_flag": finish_flag,
        "acstate": acstate,
        "chargebars": chargebars,
        "ignition": ignition,
        "parked": drive_status == 1,
        "direction_forward": drive_status == 4,
        "lease_contract": lease_contract == 1,
        "soc": soc,
        "soc_display": soc_display,
        "soc_display_int": soc_display_int,
        "cabin_temp": cabin_temp,
        "gids": gids,
        "soh": soh,
        "obc_6kw_exist": obc_flag,
        "batt_heat_exist": False,
        "batt_heat_active": False,
        "capacity_bars": capacity_bars,
        "1kw_chg": chg_time_1,
        "3kw_chg": chg_time_2,
        "6kw_chg": chg_time_3,
        "gids_when_new": gids_when_new
    }, all_li


def make_ack_response(vin: str, dcm_id: str, dest_id: int, src_id: int, prov_type: int, flag: int, value: int) -> bytes:
    acp_msg = bytearray()
    acp_msg += composer.VehDesc(vin=vin, dcm=dcm_id).encode()
    acp_msg += dest_id.to_bytes(1, "little")  # dest ID
    acp_msg += src_id.to_bytes(1, "little")  # src ID
    acp_msg += composer.EVCommandTail(command=0).encode()
    acp_msg += composer.ServiceProvisioning(entries=[composer.ServiceProvisioningService(prov_type, flag == 1, value)]).encode()

    msg = bytearray()
    msg += composer.AppHeader(app_id=0x1d, mcf=3, length=len(acp_msg), special_flag=1).encode()
    msg += acp_msg
    return msg